// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from '@prismicio/client';
import type * as prismicT from '@prismicio/types';

type Simplify<T> = {
	[KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
interface HomepageDocumentData {
	/**
	 * Name field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	name: prismicT.KeyTextField;
	/**
	 * Role field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: developer
	 * - **API ID Path**: homepage.role
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	role: prismicT.KeyTextField;
	/**
	 * Meta description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	meta_description: prismicT.KeyTextField;
	/**
	 * Biography field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.biography
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	biography: prismicT.RichTextField;
	/**
	 * Primary color field in *Homepage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.primary_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/color
	 *
	 */
	primary_color: prismicT.ColorField;
	/**
	 * Secondary color field in *Homepage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.secondary_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/color
	 *
	 */
	secondary_color: prismicT.ColorField;
	/**
	 * Mail field in *Homepage*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.mail
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	mail: prismicT.LinkField;
	/**
	 * Twitter field in *Homepage*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.twitter
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	twitter: prismicT.LinkField;
	/**
	 * Medium field in *Homepage*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.medium
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	medium: prismicT.LinkField;
	/**
	 * Github field in *Homepage*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.github
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	github: prismicT.LinkField;
	/**
	 * Linkedin field in *Homepage*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.linkedin
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	linkedin: prismicT.LinkField;
	/**
	 * Malt field in *Homepage*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.malt
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	malt: prismicT.LinkField;
	/**
	 * Technos field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.technos[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/group
	 *
	 */
	technos: prismicT.GroupField<Simplify<HomepageDocumentDataTechnosItem>>;
	/**
	 * Work experiences field in *Homepage*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.work_experiences[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/group
	 *
	 */
	work_experiences: prismicT.GroupField<Simplify<HomepageDocumentDataWorkExperiencesItem>>;
}
/**
 * Item in Homepage → Technos
 *
 */
export interface HomepageDocumentDataTechnosItem {
	/**
	 * Label field in *Homepage → Technos*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.technos[].label
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	label: prismicT.KeyTextField;
	/**
	 * Certification field in *Homepage → Technos*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.technos[].certification
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	certification: prismicT.LinkField;
	/**
	 * Certification label field in *Homepage → Technos*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.technos[].certification_label
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	certification_label: prismicT.KeyTextField;
}
/**
 * Item in Homepage → Work experiences
 *
 */
export interface HomepageDocumentDataWorkExperiencesItem {
	/**
	 * Company field in *Homepage → Work experiences*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.work_experiences[].company
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	company: prismicT.KeyTextField;
	/**
	 * From field in *Homepage → Work experiences*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.work_experiences[].from
	 * - **Documentation**: https://prismic.io/docs/core-concepts/date
	 *
	 */
	from: prismicT.DateField;
	/**
	 * To field in *Homepage → Work experiences*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.work_experiences[].to
	 * - **Documentation**: https://prismic.io/docs/core-concepts/date
	 *
	 */
	to: prismicT.DateField;
	/**
	 * Experience field in *Homepage → Work experiences*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.work_experiences[].experience
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	experience: prismicT.RichTextField;
}
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;
export type AllDocumentTypes = HomepageDocument;
declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}
	namespace Content {
		export type {
			HomepageDocumentData,
			HomepageDocumentDataTechnosItem,
			HomepageDocumentDataWorkExperiencesItem,
			HomepageDocument,
			AllDocumentTypes
		};
	}
}
